#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/AI_READ_ME_MAP.md"

emit_tree() {
  local label="$1"
  local path="$2"
  local depth="$3"

  if [ ! -d "$path" ]; then
    return
  fi

  echo "## $label"
  echo '```text'
  find "$path" -maxdepth "$depth" -mindepth 1 \
    | sed "s#^$ROOT/##" \
    | sort
  echo '```'
  echo
}

{
  echo "# AI_READ_ME_MAP (repo-local)"
  echo
  echo "Generated by: \`bash scripts/gen_ai_read_me_map.sh\`"
  echo "Do not hand-edit. Regenerate after structure changes."
  echo
  echo "## Top-level"
  echo '```text'
  find "$ROOT" -maxdepth 1 -mindepth 1 \
    ! -name '.git' \
    | sed "s#^$ROOT/##" \
    | sort
  echo '```'
  echo

  emit_tree "canvas-editor-app/src" "$ROOT/canvas-editor-app/src" 3
  emit_tree "canvas-app/src (reference)" "$ROOT/canvas-app/src" 3
  emit_tree "js (legacy)" "$ROOT/js" 2
  emit_tree "docs" "$ROOT/docs" 2
  emit_tree "scripts" "$ROOT/scripts" 2
  emit_tree "codex_tasks" "$ROOT/codex_tasks" 3
} > "$OUT"

echo "Updated $OUT"
